### ISSUE TITLE
If possible fix webpage so that includes link to source code like bbousims

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/bboudata#18]
<img width="1162" alt="Screenshot 2024-04-29 at 18 15 18" src="https://github.com/poissonconsulting/bboudata/assets/613671/60569a08-579a-4d87-87ec-9a28b384b01c">

vs

<img width="1273" alt="Screenshot 2024-04-29 at 18 13 32" src="https://github.com/poissonconsulting/bboudata/assets/613671/7d99ff23-d744-4757-8e20-b56baf9151bf">

**Comment by aylapear** [comment]
This can be done by adding this line to the Description file

```
BugReports: https://github.com/poissonconsulting/bbousims/issues
```

Not sure this is entirely correct as its links to the issues in the other package not the issues in bboudata.

**Comment by joethorley** [comment]
Yes sorry I was unclear I meant add links to the bboudata issues and code. So it seems we just need to add

```
BugReports: https://github.com/poissonconsulting/bboudata/issues
URL: https://github.com/poissonconsulting/bboudata, https://poissonconsulting.github.io/bboudata/
```

to the DESCRIPTION file and then run `usethis::use_tidy_description()` so in the correct arrangement.

**Comment by joethorley** [comment]
in PR #20
